### ISSUE TITLE
Windows: Nammu very slow

### ISSUE THREAD

**Issue by niekveldhuis** [oracc/nammu#157]
On windows platform (Windows 8), Nammu reacts very slowly to keystrokes (first is OK - afterwards it takes multiple seconds per keystroke).

**Comment by raquel-ucl** [comment]
Hi Niek,

What keystrokes are they? I'll try to reproduce it as well. Also how big is the file? We have the latest corpus, so probably project and filename would suffice for me to find it. 

Thanks.

**Comment by niekveldhuis** [comment]
Hi Raquel,

The file I used is not up yet - it is not small, but also not terribly
large (attached). I noticed first with repeated keystrokes (like going left
with LEFT-ARROW, or deleting a word with Backspace). Then I noted that it
also happens when entering a word like lugal[king]N. BTW - I entered that
word as a lemmatization in order to trigger an error (test the error
checking). It did not actually trigger an error - are lemmatization errors
not covered yet?

Niek

**Comment by raquel-ucl** [comment]
Hi Niek,

I'm afraid if you attached your file to the GitHub email instead of uploading it here, the attachment gets lost, so I can't see it. Uploading it here would make it public since this is a public repository, so you can just send an email to my normal email address and attach it there.

We have done some tests and you are right, things get slow quicker than I thought. We can easily avoid things like left/right/up/down arrow keys triggering syntax highlighting, since those don't imply changes in the text, but I'm afraid for the rest it won't be a quick change and it'll have to wait until after the conference.

For the validation and lemmatisation errors, Nammu does support those and should highlight errors and display the text of the error in the console and in a tooltip. I'll double check when you send me the file and the instructions to replicate the error.

Thanks!

**Comment by raquel-ucl** [comment]
Made some fixes in #164 so that  left/right/up/down arrow keys  as well as control, shift, cmd, caps lock and other that don't alter the text won't trigger syntax highlight.

**Comment by niekveldhuis** [comment]
I have tried Nammu 0.3.1 - typing is still extremely slow. I (hand-) timed typing 

#this is a test

it took 70 seconds.
Moving around with the cursor is indeed not a problem anymore. Highlighting and deleting a block of characters is not a problem either.
Niek

**Comment by raquel-ucl** [comment]
Was that line you tested the only line in the file, or was this added to a longer file? I've observed Nammu starts struggling after 600-700 lines. 

We do need to work on caching the syntax highlighting so it doesn't go through the whole text every time a character is added.

**Comment by niekveldhuis** [comment]
This was a longer file, indeed. Haven't tested on new file yet!
Niek

**Comment by niekveldhuis** [comment]
Update: tried Nammu 0.3.1 on (older) Windows 10 laptop at home. Creating a new file, typing, getting errors from the server all works. Opening a long file works, but checking that long file does not work ('validation did not return errors' - even with errors in the first few lines)

**Comment by raquel-ucl** [comment]
Yes, I have been able to reproduce this problem with the validation. I'll have a look at what's going on in the communications with the server and let you know.

**Comment by raquel-ucl** [comment]
Might be worth to investigate if using something like [this](http://docs.oracle.com/javase/6/docs/api/javax/swing/SwingWorker.html) would be of any help.

**Comment by raquel-ucl** [comment]
Issue solved in Nammu 0.8.
