### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by niekveldhuis** [oracc/nammu#170]
Nammu 0.3.1 installed on a MacBook Pro, OS X Yosemite: It starts as expected, it does the coloring of the various types of data correctly, etc. The validation process does not work properly. It does find errors in the ATF syntax, but it does not find transliteration errors or lemmatization errors. See attached screen shot: line 14 has a transliteration error (tuu is not a valid sign) and 15 has a lemmatization error (should be #lem: u; u). The wireless is working fine; Emacs *does* find these errors.
Also installed Nammu 0.3.1 on a Windows desktop (ethernet) - same validation issues.

<img width="906" alt="screen shot 2016-07-08 at 4 39 26 pm" src="https://cloud.githubusercontent.com/assets/15022349/16704338/a4b21a78-452a-11e6-94f9-e70bd5a33955.png">
<img width="806" alt="screen shot 2016-07-07 at 11 47 25 am" src="https://cloud.githubusercontent.com/assets/15022349/16704341/a7d33f66-452a-11e6-83b6-49b9d23a0f02.png">

**Comment by jnovotny-lmu** [comment]
@oracc/ucl-rsdg (cc: @EleanorRobson) 
I am also using Nammu 0.3.1 installed on a MacBook Pro, OS X Yosemite. I am experiencing similar uses with certain files. I can introduce multiple errors into those files and the atf validate does not function (nor does the lemmatize atf). See the screen shots below.
<img width="606" alt="screen shot 2016-07-09 at 6 38 21 am" src="https://cloud.githubusercontent.com/assets/19565350/16706126/5b2ec93e-45a0-11e6-87f3-f695978eee16.png">
<img width="569" alt="screen shot 2016-07-09 at 6 39 03 am" src="https://cloud.githubusercontent.com/assets/19565350/16706127/608d49c8-45a0-11e6-8886-5bc45546c282.png">

I will send the ATF files via e-mail.

**Comment by niekveldhuis** [comment]
Update: tried validation on two laptops today: same Mac Book Pro as yesterday (but now through a wireless at home) and Windows 10. Both work for (short) new files. Not for longer (existing) files). Same for validation and lemmatization.

**Comment by raquel-ucl** [comment]
I have found the origin of the problem.

Turns out files with spaces in their name make the server confused. It could be the Emacs plugin is translating this spaces into something else to work around the problem. That explains why validation/lemmatisation works in Emacs but doesn't in Nammu. I'll work around it as well for now and release a new version today or Wednesday (I'm away at a conference tomorrow).
 
Some more in-depth info about this which could be helpful to @stinney:

Looking at the server logs after validating both files with and without spaces in their filenames, I observed this problem happens when the server runs `xsystem  /home/oracc/bin/ox`. In the case of filename with no spaces (`Nabonidus0003.atf`):

```
xsystem /home/oracc/bin/ox -l /home/oracc/tmp/sop/KnHijH/oracc.log -cvmD 00atf/Nabonidus0003.atf
```

In the other case with spaces in the file name (`Nabonidus 0003.atf`):

```
xsystem /home/oracc/bin/ox -l /home/oracc/tmp/sop/90pGoG/oracc.log -cvmD 00atf/Nabonidus
ox: nothing to do
```

In the first case, `oracc.log` contains the list of validation errors, and in the second it is empty.

I would expect the server to complain or return some kind of information to the client when ox returns "nothing to do" because the input file is wrong. For now I'll work around it in Nammu.

**Comment by EleanorRobson** [comment]
In fact, the Oracc documentation explicitly deprecates using spaces in the file names of portal pages (http://oracc.museum.upenn.edu/doc/help/portals/buildinganespsite/#h_namesandnaming). I wonder if we should deprecate them in ATF filenames too.

**Comment by raquel-ucl** [comment]
Yes, I can make Nammu warn users not to save files with name spaces on them, or open them. But for now I'll just mock the Emacs plugin behaviour and work around it. I'll create an issue to discuss about this when you're back.
