### ISSUE TITLE
running 0.5.3 in Windows 8

### ISSUE THREAD

**Issue by niekveldhuis** [oracc/nammu#197]
To help us understand and resolve your issue please check that you have provided
as much of the information below as possible:

Nammu-0.5.3.jar
1.8.0_111
Windows 8
Double clicking on the jar file opens the image. After a few seconds it disappears and nothing else happens.

Opening through Command (java -jar Nammu-0.5.3.jar), while in the directory where the file resides.

1. initially the file was located in the directory 'c:\Users\veldhuis\My Documents\Nammu' The file initially started doing something (the image appears) but then complained it couldn't find the file:
Exception in thread : "MainThread" Traceback (most recent call last):
File: "<string>", line 3, in <module>
File: "<string>", line 3, in <module>
File "__pyclasspath__/nammu/main.py", line 27 in main 
File "__pyclasspath__/nammu/controller/NammuController.py", line 72 in __init__
File "__pyclasspath__/nammu/controller/NammuController.py", line 676 in setup_logger
File "__pyclasspath__/nammu/utils/__init.py", line 135, in get_yaml_config
File "__pyclasspath__/nammu/utils/__init.py", line 161, in update_yaml_config
File "__pyclasspath__/nammu/utils/__init.py", line 161, in update_yaml_config
File "C:\Users\veldhuis\My Documents\Nammu\nammu-0.5.3.jar\Lib\zipfile.py", line 754, in __init__
IOError: {Errorno 2] No such file or directory: '/C:/Users/veldhuis/My%20Documents/Nammu/nammu-0.5.3.jar'

2. I figured the problem was the space in the directory name so I moved the file to C:\Users\Veldhuis and tried to run again. The image opens; I get a long list of DEBUG lines in the following format:
2016-12-07 09:56:55 - NammuController - DEBUG - Comparing install and local settings files...
2016-12-07 09:56:55 - NammuController - DEBUG - projects: cmawro: None --> Using local values.
(which I guess is good)

Then the error messages:
Exception in thread : "MainThread" Traceback (most recent call last):
File: "<string>", line 3, in <module>
File: "<string>", line 3, in <module>
File "__pyclasspath__/nammu/main.py", line 27 in main 
File "__pyclasspath__/nammu/controller/NammyController.py", line 75 in __init__
File "__pyclasspath__/nammu/utils/__init.py", line 135, in get_yaml_config
File "__pyclasspath__/nammu/utils/__init.py", line 179, in update_yaml_config

KeyError: 'find_keystrokes'

(unfortunately I had to type these messages up - I do not know how to copy them from Command prompt - may have small mistakes).

**Comment by raquel-ucl** [comment]
Hi Niek,

Thanks a lot for the report.

We identified this problem when I last was with Eleanor and registered it in #193. 

There is a config file in a folder called `.nammu` inside your home directory (I think it should be in `C:/Users/veldhuis/.nammu`). That folder contains a `settings.yaml` file, which contains the user's configuration for Nammu, including keystrokes. The new version has new keystrokes for the find/replace functionality, and when you first open it, it tries to update that file and fails. I am working on fixing the problem, so you can wait until the next version which I'll release next week, or otherwise a quick fix is to replace that file (probably located in `C:/Users/veldhuis/.nammu/settings.yaml`) with [this one](https://github.com/oracc/nammu/blob/master/resources/config/settings.yaml). Then try to reopen and it should all be ok. 

Another thing to note is also inside that same folder there is a log file called `nammu.log`. That file contains all the output from every time you have ever run Nammu. This would help you next time you need to send a report, so you can send me the file, or open it and copy the relevant bits. I think you can also right click on the title bar of the windows console, then choose Edit->Mark, if you want to copy what you see on the Windows console.

Please let me know if this helps or if there is something else I can do.

**Comment by niekveldhuis** [comment]
Thanks, Raquel. I installed the settings.yaml - I still get essentially the
same behavior. The image opens and then disappears. When starting from the
console I get the same error messages as yesterday:

Exception in thread : "MainThread" Traceback (most recent call last):
File: "(string)", line 3, in (module)
File: "(string)", line 3, in (module)
File "__pyclasspath__/nammu/main.py", line 27 in main
File "__pyclasspath__/nammu/controller/NammyController.py", line 75 in __
init__
File "__pyclasspath__/nammu/utils/__init.py__", line 135, in get_yaml_config
File "__pyclasspath__/nammu/utils/__init.py__", line 179, in
update_yaml_config

KeyError: 'find_keystrokes'

The Nammu.log that you referred to does list all the DEBUG messages, but
the not the Java error messages.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by raquel-ucl** [comment]
Can you paste here the content of the `settings.yaml` you pasted? It should be version 0.5 and have a `find_keystrokes` element inside. When I first replied to your issue this morning I linked to the wrong version of it, but corrected it later. If you got the settings file from the link in an email and not the GH issue webpage, chances are you got the wrong one. GH doesn't resend emails when an issue is edited.  

In any case I'm working on fixing this right now, so you might prefer to wait.

**Comment by niekveldhuis** [comment]
Got it from the email, indeed. I got settings.yaml version 0.2. I'll wait -
I won't have much time for playing with it today anyway.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by niekveldhuis** [comment]
At least I managed to open Nammu with the settings.yaml version .05!

Thanks,

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by raquel-ucl** [comment]
Great! I just now fixed the problem as well :) 
I won't make a release yet because there are still some other things to finalise.
If you are going to play with large files, I made a temporary fix for Eleanor that is included in your JAR version that switches off the syntax highlight. It should work if you do `Ctrl+T`.  
However please note this release you are playing with is not official and therefore likely to break! Do send reports if you find problems.

**Comment by niekveldhuis** [comment]
I know - it's a draft. The large file thing is important to me.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by raquel-ucl** [comment]
Fixed in #193, closing.
