### ISSUE TITLE
Unable to open Nammu

### ISSUE THREAD

**Issue by dreilaendereck** [oracc/nammu#299]
* Nammu's version: Nammu-1.0.0.jar
* Java version: Java 8 update 151
* Computer Platform: Windows 10
* When I try to open Nammu, I get the ORACC splash screen which remains for about 20 seconds, at which point it disappears and the program does not open.
I've tried to run the command line suggested in your Troubleshooting section, with this result:
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 3, in <module>
  File "__pyclasspath__/nammu/main.py", line 27, in main
  File "__pyclasspath__/nammu/controller/NammuController.py", line 72, in __init__
  File "__pyclasspath__/nammu/utils/__init__.py", line 133, in get_yaml_config
  File "__pyclasspath__/nammu/utils/__init__.py", line 330, in copy_yaml_to_home
UnboundLocalError: local variable 'zf' referenced before assignment

![image](https://user-images.githubusercontent.com/33158275/32112503-78ad3752-bb0b-11e7-8d31-fce2f2062810.png)

Thank you for your help.

**Comment by raquel-ucl** [comment]
Thanks for the report @dreilaendereck and sorry Nammu is not working for you at the moment.

There seems to be a problem with the code trying to access the contents of the jar file. I have tested this some time ago in Windows, but not Windows 10. It might be the path to the jar automatically built in the code is wrong.

This is the part of the code the problem is coming from:

```
def copy_yaml_to_home(jar_file_path, source_rel_path, target_path):
    '''
    Opens Nammu's jar as a zip file, looks for the yaml config file and copies
    it to ~/.nammu.
    '''
    try:
        zf = zipfile.ZipFile(jar_file_path, 'r')
    except zipfile.BadZipfile:
        shutil.copyfileobj(file(source_rel_path, "wb"),
                           file(target_path, "wb"))
    else:
        lst = zf.infolist()
        for zi in lst:
            fn = zi.filename
            if fn.lower() == source_rel_path:
                source_file = zf.open(fn)
                target_file = file(target_path, "wb")
                with source_file, target_file:
                    shutil.copyfileobj(source_file, target_file)
    finally:
        zf.close()
```

My guess is there might have been an exception when trying to do `zf = zipfile.ZipFile(jar_file_path, 'r')` and the `finally` part which is always executed (with or without the exception happening) is trying to close `zf` even though it doesn't exist. 

We'll test it in Windows 10 next week to see if the problem is related to that, and add some logging functionality to this part of the code, to be able to see the contents of the `jar_file_path` variable.

**Comment by ageorgou** [comment]
I cannot replicate this on Windows 7, but will also test it on Windows 10. I think we can avoid the problem by rewriting those lines, but we need to check that the path to the zip file is correct anyway.

**Comment by ageorgou** [comment]
Managed to replicate this under these conditions:
- there is no previous installation of Nammu (or at least no .nammu directory)
- the directory where the jar file is located contains an ! in its name, e.g. "D:/my!folder/nammu-1.0.0.jar".

In this case, the `path_to_jar` in `get_yaml_config` will be "D:/my" instead of the full folder name, and the jar will not be accessible. I am a bit surprised that this doesn't cause an error when the exception is caught (line 318-319) - it seems that the "plan B" file copying fails silently.

Plan for fixing (if this is indeed the problem):
- [ ] Take everything before the final ! as the path to the jar, instead of before the first !
- [ ] Rewrite`copy_yaml_to_home` to use a context manager so that `zf` cannot be referenced if not initialised
- [ ] Check whether the backup copy plan (lines 318-319) works as intended, so that there is a config file created in any case

**Comment by ageorgou** [comment]
Hi @dreilaendereck,

We may have an idea of why the problem occurs but would appreciate some more information to confirm. Could you please give us the full path to the folder where the Nammu jar file is located?

Thanks in advance!

**Comment by dreilaendereck** [comment]
Hello,


Thank you for trying to fix this problem for me. The complete path is C:\Users\Brandon Post\Desktop\Lindsey Grad School\UofT\BATCUL.  I have the same issue, however, when I leave Nammu in the download folder.


Thanks!

________________________________

**Comment by ageorgou** [comment]
Hi @dreilaendereck,

Thanks for the information. I'm fairly confident that the error is because of the spaces in the path. Sorry about that! It's not very complicated to change, and I'm working on a fix.

**Comment by raquel-ucl** [comment]
@ageorgou since fixing the problem and be able to compile the jar is going to take a while, can you prepare a jar for @dreilaendereck with the fixed version, just so he can test it? Then we'll work on the maven problem on a separate issue.

**Comment by ageorgou** [comment]
Hi @dreilaendereck,

Sorry for the delay. We have created a temporary release that fixes your issue while we work on an official update. You can download it from [this link](https://www.dropbox.com/s/rthjt8fu72oo5g7/nammu-1.0.0b.jar?dl=0). Please let us know how you get on!

**Comment by dreilaendereck** [comment]
Hi @ageorgou,

It worked! Thanks so much for your work on this issue!
