### ISSUE TITLE
can't open Nammu

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#339]
When I try to open Nammu I get an error message (screenshot attached). Have tried reinstalling but that doesn't help.
![nammu_fail](https://user-images.githubusercontent.com/29441637/44164097-15bacb00-a093-11e8-99c0-f9b44b133792.jpeg)

**Comment by EleanorRobson** [comment]
Sorry you've had such a rubbish week with Oracc! I just tested Nammu 1.2 today, and we're planning to  launch it on Monday. But you can grab it now from https://github.com/oracc/nammu/releases (It got out of sync with Java upgrades; this update should fix that.)

If you have any problems, let us know here and Stuart will take a look in the morning.

**Comment by zarpanitu** [comment]
Thanks - but I see 1.0.1 there, not 1.2? I tried 1.0.1 and that also won't open

**Comment by EleanorRobson** [comment]
Ah, Stuart must have done something cunning with the perms so that only a few can see it. Can you hang on until he's back at work tomorrow?

**Comment by zarpanitu** [comment]
Sure, thanks

**Comment by sgrieve** [comment]
Hi @zarpanitu The new version of Nammu that Eleanor mentioned should be out by the end of the week. In the meantime we have released a temporary version that should solve your problems:

https://github.com/oracc/nammu/releases/download/1.0.1/nammu-1.0.1.jar

Please let me know if this doesn't work and we will get you a copy of 1.2 asap.

**Comment by zarpanitu** [comment]
Thanks Stuart - in fact 1.0.0 still works on my desktop, so it's not urgent as I can do the work there instead of on my laptop.

**Comment by raquel-ucl** [comment]
Hi @zarpanitu - did you have a chance to test the jar Stuart linked to? 

We found a bug that we documented in #341, so we won't be making a release until that is fixed. I will be working on it from tomorrow and keep you updated, but please feel free to use the temporary version Stuart mentioned above in the meanwhile.

**Comment by zarpanitu** [comment]
Hi Raquel, I had already tried 1.0.1 and that also wouldn't open on my laptop.

**Comment by raquel-ucl** [comment]
Hi again @zarpanitu: I have sent you a collaborator invite so you can access the new release I've made just to check if you can open it in your laptop. If has the latest features, but it still needs some refactoring and bug fixing - specially within undo/redo actions which are buggy at the moment.

Please let me know if you haven't received the collaborator invite. You will need to accept in order to access the release I've uploaded here:

https://github.com/oracc/nammu/releases/tag/untagged-573c2371fd93ec9406d3

**Comment by zarpanitu** [comment]
Hi Raquel,
Thanks, I got the invitation. But when I go to the link, then I can't seem to download the file. I click on it but nothing happens.

**Comment by raquel-ucl** [comment]
Sorry, the jar was not there! I've updated it now. You can get the jar directly from here:
https://github.com/oracc/nammu/releases/download/1.2.1-alpha/nammu-1.2.0-alpha.jar

**Comment by raquel-ucl** [comment]
I'm sorry this is not working well for you. Thanks a lot for your patience so far :)

Could you try to open the jar from a console running ```java -jar <path to nammu's jar file>```? 

What's the operating system of your laptop? If you have a Mac or a Linux machine, and you have the file in your downloads, it would be:

```
java -jar ~/Downloads/nammu-1.2.0-alpha.jar
```

If you have Windows it might instead be:

```
java -jar %HOME%\Downloads\nammu-1.2.0-alpha.jar
```

If you can't run this for some reason, it might help us if you send or copy-paste the last lines of Nammu's logfile and the contents of Nammu's settings. You will find a folder called ".nammu" in your home folder (that is `~/.nammu` in Mac or Linux, or `%HOME%\.nammu` in Windows). It contains a file called "nammu.log" and another called "settings.yaml". If you could share those with us that'd be great. 

Lastly, it would also help if you could send us the output of this command so we know what your Java version is:

```
java -version
```

Hopefully we'll get to the root of the problem soon and produce a fix for you.

**Comment by zarpanitu** [comment]
Hi, thanks, I just tried to run it on my Macbook Air (OS 10.13.6) using java -jar ~/Downloads/nammu-1.2.0-alpha.jar, and the last line reads "TypeError: 'NoneType' object is unsubscriptable"

My Java version is 1.8.0_181

I see there are two nammu.log files in `/.nammu, I'm attaching both
[nammu1.log](https://github.com/oracc/nammu/files/2311639/nammu1.log)
[nammu.log](https://github.com/oracc/nammu/files/2311637/nammu.log)

Github won't allow me to upload the .yaml file

**Comment by raquel-ucl** [comment]
Thanks @zarpanitu.

I think I'm going to need all the lines in the output of the `java -jar` command before the one you pasted above, to know where the error is coming from.

The last lines of your log do mention some changes in your settings file, so it would be interesting to see it so I can replicate your error and fix it. You can add it here by renaming it to `settings.txt`, or send it me by email. I'll email you in a moment so you have my address.

Again, thanks for your patience! This will help making Nammu work on computers with similar problems in the future, once we fix the error :)

**Comment by raquel-ucl** [comment]
Just for future reference, this is the error @zarpanitu circulated:

```
java -jar ~/Downloads/nammu-1.2.0-alpha.jar
Exception in thread "MainThread" Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "<string>", line 3, in <module>
  File "__pyclasspath__/nammu/main.py", line 27, in main
  File "__pyclasspath__/nammu/controller/NammuController.py", line 68, in __init__
  File "__pyclasspath__/nammu/utils/__init__.py", line 144, in get_yaml_config
  File "__pyclasspath__/nammu/utils/__init__.py", line 253, in update_yaml_config
  File "__pyclasspath__/nammu/utils/__init__.py", line 236, in get_config_versions
TypeError: 'NoneType' object is unsubscriptable
```

This error indicates that Nammu can't find the local version of the settings located in ~/.nammu/settings.yaml in order to compare with the one embedded in Nammu's jar in order to check for updates.

Heather has sent her settings.yaml file and it is empty. I'm checking with her if this is a problem trying to share the file, or it is indeed empty. The settings file being empty can be a cause for the error message above to show up.

The proposed solution is to delete the local settings file in ~/.nammu/settings.yaml and reopen Nammu. This should be all that is needed. The only problem with this solution is that whatever settings Heather has changed (e.g. server location, preferred folder to save/load files, project list to populate new ATF's dropdown, etc.) will be lost and become the default ones. I have suggested her to copy-paste the contents of the settings file in her desktop machine, which might be more customised to her work.

I'm following this with Heather separately by email. I'll keep this issue update once I hear back from her with the proposed solution after her holidays.

**Comment by zarpanitu** [comment]
I can confirm that deleting the settings file worked and I can now open Nammu.

**Comment by raquel-ucl** [comment]
Thanks @zarpanitu ! I'll try to add a change in Nammu so it displays a better error message next time it fails due to the settings file being corrupt :)
