### ISSUE TITLE
Nammu not lemmatizing files with new but unrecognized P-numbers

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#342]
I have entered the new P-numbers for my Nappahu corpus in my .atf files, but Nammu will not lemmatize them: I get the warning message “P512081 not in main catalog (new P-IDs may not register for 48 hours)". However, if I change the number to a temporary one (e.g. X000001) then the lemmatization proceeds as expected.

Is it possible to have Nammu warn about unregistered P-numbers but go ahead and lemmatize the texts anyway? It's somewhat time-consuming to have to fiddle with temporary numbers.

**Comment by niekveldhuis** [comment]
Heather,

This an ORACC issue, rather than a Nammu issue. I always replace such P
numbers by the identical X number (in your case  X512081) and all I need to
do is swap Ps for Xs at some point. It is a nuisance - I agree, but is
important to have that check in place.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by zarpanitu** [comment]
Thanks, Niek - I'll do as you suggest.
