### ISSUE TITLE
Toggling/untoggling arabic pane needs more work

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#353]
When working with an arabic file, the editor is automatically split in two.

If then another type of toggle is selected, this hides the Arabic editor, including the Arabic texts. When trying to toggle the Arabic mode again, it assumes this is to create a new file with an Arabic translation. Logic about this needs to be reworked.

**Comment by raquel-ucl** [comment]
1. In arabic mode edition, without saving latest arabic pane changes, choose split horizontal/vertical
1. Choose split again so it actually happens (this shouldn't need two steps!)
1. The arabic text is gone!
1. Choose arabic mode again - it asks to save changes and tries to open a new file !

**Comment by giordano** [comment]
I'm looking into this.  I think that the problem is that `AtfAreaView.setup_edit_area` doesn't check current setup before going on, so it doesn't know if the current split view is showing contains an Arabic pane or not.

Also without Arabic pane, if there is a horizontal split view, toggling vertical split actually toggles the horizontal split.  The same happens if there is vertical split and you toggle horizontal split.  Thus, this issue is not specific to Arabic pane but it's definitely part of the problem
